CREATE TABLE IF NOT EXISTS community (
    id MEDIUMINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(500) NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS post (
    id INT NOT NULL AUTO_INCREMENT,
    content TEXT NOT NULL,
    visibility ENUM('NORMAL', 'HIDDEN') NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(id),
    INDEX IDX_BY_CREATED_AT (created_at DESC, id DESC)
);

CREATE TABLE IF NOT EXISTS post_communities (
    post_id INT NOT NULL,
    community_id MEDIUMINT NOT NULL,
    PRIMARY KEY(post_id, community_id)
);